name: Docker Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [ labeled ]
# Ensures that only the latest commit is running for each PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Docker-Tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Containerize Artifactory
        run: ./start.sh
        working-directory: tests/resources/docker/artifactory
        env:
          RTLIC: ${{secrets.RTLIC}}

      - name: Install
        run: npm install --no-fund

      - name: Wait for Artifactory to finish loading
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost:8082"
          responseCode: 200
          timeout: 600000
          interval: 500

      - name: Run tests
        run: npm t
        env:
          ADO_JFROG_PLATFORM_URL: http://localhost:8082
          ADO_JFROG_PLATFORM_USERNAME: admin
          ADO_JFROG_PLATFORM_PASSWORD: password
          ADO_JFROG_PLATFORM_DOCKER_DOMAIN: 127.0.0.1:8082
          ADO_SKIP_TESTS: unit,proxy,generic,installer,npm,maven,gradle,conan,nuget,dotnet,go,pip,distribution
